//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTV.Scheduler.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewScheduleDetails {
            get {
                return ((bool)(this["ViewScheduleDetails"]));
            }
            set {
                this["ViewScheduleDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewNotifications {
            get {
                return ((bool)(this["ViewNotifications"]));
            }
            set {
                this["ViewNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewGrid {
            get {
                return ((bool)(this["ViewGrid"]));
            }
            set {
                this["ViewGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int RichLogMaxLenght {
            get {
                return ((int)(this["RichLogMaxLenght"]));
            }
            set {
                this["RichLogMaxLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2012-03-28")]
        public global::System.DateTime LastScheduleChangeDateTime {
            get {
                return ((global::System.DateTime)(this["LastScheduleChangeDateTime"]));
            }
            set {
                this["LastScheduleChangeDateTime"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeepAliveCallBackEnabled {
            get {
                return ((bool)(this["KeepAliveCallBackEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int KeepAliveCallBackTimerInterval {
            get {
                return ((int)(this["KeepAliveCallBackTimerInterval"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-03-28")]
        public global::System.DateTime LastVideoContentLockedOn {
            get {
                return ((global::System.DateTime)(this["LastVideoContentLockedOn"]));
            }
            set {
                this["LastVideoContentLockedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-03-28")]
        public global::System.DateTime LastVideoContentScheduledOn {
            get {
                return ((global::System.DateTime)(this["LastVideoContentScheduledOn"]));
            }
            set {
                this["LastVideoContentScheduledOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-03-28")]
        public global::System.DateTime LastVideoContentRemovedOn {
            get {
                return ((global::System.DateTime)(this["LastVideoContentRemovedOn"]));
            }
            set {
                this["LastVideoContentRemovedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastRemove {
            get {
                return ((string)(this["lastRemove"]));
            }
            set {
                this["lastRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("236")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28/03/2013")]
        public string PosterAutomaticRecordLastSent {
            get {
                return ((string)(this["PosterAutomaticRecordLastSent"]));
            }
            set {
                this["PosterAutomaticRecordLastSent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-22")]
        public global::System.DateTime LastCategoryItemsChangedOn {
            get {
                return ((global::System.DateTime)(this["LastCategoryItemsChangedOn"]));
            }
            set {
                this["LastCategoryItemsChangedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastVideoContentExpiredOn {
            get {
                return ((global::System.DateTime)(this["LastVideoContentExpiredOn"]));
            }
            set {
                this["LastVideoContentExpiredOn"] = value;
            }
        }
    }
}
