//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Net;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 

namespace MTV.Library.Core.Proxy
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Service1Soap", Namespace = "http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class MMPCProxyProvider : System.Web.Services.Protocols.SoapHttpClientProtocol {

        private System.Threading.SendOrPostCallback TestWSOperationCompleted;

        private System.Threading.SendOrPostCallback TestAppOperationCompleted;

        private System.Threading.SendOrPostCallback EncapsulatorHasSentContentOperationCompleted;

        private System.Threading.SendOrPostCallback CreaScheduleItemOperationCompleted;

        private System.Threading.SendOrPostCallback ModificaScheduleItemOperationCompleted;

        private System.Threading.SendOrPostCallback EliminaScheduleItemOperationCompleted;

        private System.Threading.SendOrPostCallback CreaTVComandaGravacioOperationCompleted;

        private System.Threading.SendOrPostCallback CreaTVComandaGravacioV2OperationCompleted;

        private System.Threading.SendOrPostCallback AturaTVComandaGravacioOperationCompleted;

        private System.Threading.SendOrPostCallback EliminaTVComandaGravacioOperationCompleted;

        private System.Threading.SendOrPostCallback EnviaCodiIDOperationCompleted;

        private System.Threading.SendOrPostCallback EnviaEntitlementOperationCompleted;

        private System.Threading.SendOrPostCallback EnviaEntitlementV2OperationCompleted;

        private System.Threading.SendOrPostCallback EnviaComandaStandByOperationCompleted;

        private System.Threading.SendOrPostCallback EnviaXMLOperationCompleted;

        private System.Threading.SendOrPostCallback AturaXMLOperationCompleted;

        private System.Threading.SendOrPostCallback EliminaContingutSTBOperationCompleted;

        private System.Threading.SendOrPostCallback ModificaContingut_content_life_mod_commandOperationCompleted;

        private System.Threading.SendOrPostCallback EnviaComandaBase64OperationCompleted;

        /// <remarks/>
        public MMPCProxyProvider(string strIP) {
            this.Url = string.Format("http://{0}/MMPC/Service1.asmx", strIP);
        }

        /// <remarks/>
        public event TestWSCompletedEventHandler TestWSCompleted;

        /// <remarks/>
        public event TestAppCompletedEventHandler TestAppCompleted;

        /// <remarks/>
        public event EncapsulatorHasSentContentCompletedEventHandler EncapsulatorHasSentContentCompleted;

        /// <remarks/>
        public event CreaScheduleItemCompletedEventHandler CreaScheduleItemCompleted;

        /// <remarks/>
        public event ModificaScheduleItemCompletedEventHandler ModificaScheduleItemCompleted;

        /// <remarks/>
        public event EliminaScheduleItemCompletedEventHandler EliminaScheduleItemCompleted;

        /// <remarks/>
        public event CreaTVComandaGravacioCompletedEventHandler CreaTVComandaGravacioCompleted;

        /// <remarks/>
        public event CreaTVComandaGravacioV2CompletedEventHandler CreaTVComandaGravacioV2Completed;

        /// <remarks/>
        public event AturaTVComandaGravacioCompletedEventHandler AturaTVComandaGravacioCompleted;

        /// <remarks/>
        public event EliminaTVComandaGravacioCompletedEventHandler EliminaTVComandaGravacioCompleted;

        /// <remarks/>
        public event EnviaCodiIDCompletedEventHandler EnviaCodiIDCompleted;

        /// <remarks/>
        public event EnviaEntitlementCompletedEventHandler EnviaEntitlementCompleted;

        /// <remarks/>
        public event EnviaEntitlementV2CompletedEventHandler EnviaEntitlementV2Completed;

        /// <remarks/>
        public event EnviaComandaStandByCompletedEventHandler EnviaComandaStandByCompleted;

        /// <remarks/>
        public event EnviaXMLCompletedEventHandler EnviaXMLCompleted;

        /// <remarks/>
        public event AturaXMLCompletedEventHandler AturaXMLCompleted;

        /// <remarks/>
        public event EliminaContingutSTBCompletedEventHandler EliminaContingutSTBCompleted;

        /// <remarks/>
        public event ModificaContingut_content_life_mod_commandCompletedEventHandler ModificaContingut_content_life_mod_commandCompleted;

        /// <remarks/>
        public event EnviaComandaBase64CompletedEventHandler EnviaComandaBase64Completed;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestWS", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestWS(string strIn) {
            object[] results = this.Invoke("TestWS", new object[] {
                    strIn});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTestWS(string strIn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestWS", new object[] {
                    strIn}, callback, asyncState);
        }

        /// <remarks/>
        public string EndTestWS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void TestWSAsync(string strIn) {
            this.TestWSAsync(strIn, null);
        }

        /// <remarks/>
        public void TestWSAsync(string strIn, object userState) {
            if ((this.TestWSOperationCompleted == null)) {
                this.TestWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestWSOperationCompleted);
            }
            this.InvokeAsync("TestWS", new object[] {
                    strIn}, this.TestWSOperationCompleted, userState);
        }

        private void OnTestWSOperationCompleted(object arg) {
            if ((this.TestWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestWSCompleted(this, new TestWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestApp", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestApp(string strIn) {
            object[] results = this.Invoke("TestApp", new object[] {
                    strIn});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTestApp(string strIn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestApp", new object[] {
                    strIn}, callback, asyncState);
        }

        /// <remarks/>
        public string EndTestApp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void TestAppAsync(string strIn) {
            this.TestAppAsync(strIn, null);
        }

        /// <remarks/>
        public void TestAppAsync(string strIn, object userState) {
            if ((this.TestAppOperationCompleted == null)) {
                this.TestAppOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestAppOperationCompleted);
            }
            this.InvokeAsync("TestApp", new object[] {
                    strIn}, this.TestAppOperationCompleted, userState);
        }

        private void OnTestAppOperationCompleted(object arg) {
            if ((this.TestAppCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestAppCompleted(this, new TestAppCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EncapsulatorHasSentContent", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EncapsulatorHasSentContent(out CEncapsulatorContent itemEncapsulatorContent) {
            object[] results = this.Invoke("EncapsulatorHasSentContent", new object[0]);
            itemEncapsulatorContent = ((CEncapsulatorContent)(results[1]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEncapsulatorHasSentContent(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EncapsulatorHasSentContent", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndEncapsulatorHasSentContent(System.IAsyncResult asyncResult, out CEncapsulatorContent itemEncapsulatorContent) {
            object[] results = this.EndInvoke(asyncResult);
            itemEncapsulatorContent = ((CEncapsulatorContent)(results[1]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EncapsulatorHasSentContentAsync() {
            this.EncapsulatorHasSentContentAsync(null);
        }

        /// <remarks/>
        public void EncapsulatorHasSentContentAsync(object userState) {
            if ((this.EncapsulatorHasSentContentOperationCompleted == null)) {
                this.EncapsulatorHasSentContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncapsulatorHasSentContentOperationCompleted);
            }
            this.InvokeAsync("EncapsulatorHasSentContent", new object[0], this.EncapsulatorHasSentContentOperationCompleted, userState);
        }

        private void OnEncapsulatorHasSentContentOperationCompleted(object arg) {
            if ((this.EncapsulatorHasSentContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncapsulatorHasSentContentCompleted(this, new EncapsulatorHasSentContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreaScheduleItem", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreaScheduleItem(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP) {
            object[] results = this.Invoke("CreaScheduleItem", new object[] {
                    strArxiu,
                    lTamany,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    nCodiUnlock,
                    dPreu,
                    strSMS,
                    dPVP,
                    strAnuncisIni,
                    strTamanysIni,
                    strDuracionsIni,
                    strAnuncisFi,
                    strTamanysFi,
                    strDuracionsFi,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreaScheduleItem(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("CreaScheduleItem", new object[] {
                    strArxiu,
                    lTamany,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    nCodiUnlock,
                    dPreu,
                    strSMS,
                    dPVP,
                    strAnuncisIni,
                    strTamanysIni,
                    strDuracionsIni,
                    strAnuncisFi,
                    strTamanysFi,
                    strDuracionsFi,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCreaScheduleItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CreaScheduleItemAsync(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP) {
            this.CreaScheduleItemAsync(strArxiu, lTamany, nPreviewTime, nPrioritat, nImmortalityTime, nActiveTime, nLifeExtension, strDiaIni, strHoraIni, strDiaFi, strHoraFi, nCodiID, nCodiUnlock, dPreu, strSMS, dPVP, strAnuncisIni, strTamanysIni, strDuracionsIni, strAnuncisFi, strTamanysFi, strDuracionsFi, strServidorFTP, strPathOrigenFTP, strUsuariFTP, strPasswordFTP, null);
        }

        /// <remarks/>
        public void CreaScheduleItemAsync(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP,
                    object userState) {
            if ((this.CreaScheduleItemOperationCompleted == null)) {
                this.CreaScheduleItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreaScheduleItemOperationCompleted);
            }
            this.InvokeAsync("CreaScheduleItem", new object[] {
                    strArxiu,
                    lTamany,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    nCodiUnlock,
                    dPreu,
                    strSMS,
                    dPVP,
                    strAnuncisIni,
                    strTamanysIni,
                    strDuracionsIni,
                    strAnuncisFi,
                    strTamanysFi,
                    strDuracionsFi,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP}, this.CreaScheduleItemOperationCompleted, userState);
        }

        private void OnCreaScheduleItemOperationCompleted(object arg) {
            if ((this.CreaScheduleItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreaScheduleItemCompleted(this, new CreaScheduleItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificaScheduleItem", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ModificaScheduleItem(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP,
                    string strArxiuModificar) {
            object[] results = this.Invoke("ModificaScheduleItem", new object[] {
                    strArxiu,
                    lTamany,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    nCodiUnlock,
                    dPreu,
                    strSMS,
                    dPVP,
                    strAnuncisIni,
                    strTamanysIni,
                    strDuracionsIni,
                    strAnuncisFi,
                    strTamanysFi,
                    strDuracionsFi,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP,
                    strArxiuModificar});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginModificaScheduleItem(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP,
                    string strArxiuModificar,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("ModificaScheduleItem", new object[] {
                    strArxiu,
                    lTamany,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    nCodiUnlock,
                    dPreu,
                    strSMS,
                    dPVP,
                    strAnuncisIni,
                    strTamanysIni,
                    strDuracionsIni,
                    strAnuncisFi,
                    strTamanysFi,
                    strDuracionsFi,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP,
                    strArxiuModificar}, callback, asyncState);
        }

        /// <remarks/>
        public string EndModificaScheduleItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ModificaScheduleItemAsync(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP,
                    string strArxiuModificar) {
            this.ModificaScheduleItemAsync(strArxiu, lTamany, nPreviewTime, nPrioritat, nImmortalityTime, nActiveTime, nLifeExtension, strDiaIni, strHoraIni, strDiaFi, strHoraFi, nCodiID, nCodiUnlock, dPreu, strSMS, dPVP, strAnuncisIni, strTamanysIni, strDuracionsIni, strAnuncisFi, strTamanysFi, strDuracionsFi, strServidorFTP, strPathOrigenFTP, strUsuariFTP, strPasswordFTP, strArxiuModificar, null);
        }

        /// <remarks/>
        public void ModificaScheduleItemAsync(
                    string strArxiu,
                    long lTamany,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    int nCodiUnlock,
                    double dPreu,
                    string strSMS,
                    double dPVP,
                    string strAnuncisIni,
                    string strTamanysIni,
                    string strDuracionsIni,
                    string strAnuncisFi,
                    string strTamanysFi,
                    string strDuracionsFi,
                    string strServidorFTP,
                    string strPathOrigenFTP,
                    string strUsuariFTP,
                    string strPasswordFTP,
                    string strArxiuModificar,
                    object userState) {
            if ((this.ModificaScheduleItemOperationCompleted == null)) {
                this.ModificaScheduleItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificaScheduleItemOperationCompleted);
            }
            this.InvokeAsync("ModificaScheduleItem", new object[] {
                    strArxiu,
                    lTamany,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    nCodiUnlock,
                    dPreu,
                    strSMS,
                    dPVP,
                    strAnuncisIni,
                    strTamanysIni,
                    strDuracionsIni,
                    strAnuncisFi,
                    strTamanysFi,
                    strDuracionsFi,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP,
                    strArxiuModificar}, this.ModificaScheduleItemOperationCompleted, userState);
        }

        private void OnModificaScheduleItemOperationCompleted(object arg) {
            if ((this.ModificaScheduleItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificaScheduleItemCompleted(this, new ModificaScheduleItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminaScheduleItem", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminaScheduleItem(string strArxiu) {
            object[] results = this.Invoke("EliminaScheduleItem", new object[] {
                    strArxiu});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEliminaScheduleItem(string strArxiu, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminaScheduleItem", new object[] {
                    strArxiu}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEliminaScheduleItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EliminaScheduleItemAsync(string strArxiu) {
            this.EliminaScheduleItemAsync(strArxiu, null);
        }

        /// <remarks/>
        public void EliminaScheduleItemAsync(string strArxiu, object userState) {
            if ((this.EliminaScheduleItemOperationCompleted == null)) {
                this.EliminaScheduleItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaScheduleItemOperationCompleted);
            }
            this.InvokeAsync("EliminaScheduleItem", new object[] {
                    strArxiu}, this.EliminaScheduleItemOperationCompleted, userState);
        }

        private void OnEliminaScheduleItemOperationCompleted(object arg) {
            if ((this.EliminaScheduleItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaScheduleItemCompleted(this, new EliminaScheduleItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreaTVComandaGravacio", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreaTVComandaGravacio(
                    string strTitol,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    float fPreu,
                    string strSMS,
                    float fPVP,
                    string strServiceID,
                    bool bTrigger,
                    int nAdultContent) {
            object[] results = this.Invoke("CreaTVComandaGravacio", new object[] {
                    strTitol,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    fPreu,
                    strSMS,
                    fPVP,
                    strServiceID,
                    bTrigger,
                    nAdultContent});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreaTVComandaGravacio(
                    string strTitol,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    float fPreu,
                    string strSMS,
                    float fPVP,
                    string strServiceID,
                    bool bTrigger,
                    int nAdultContent,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("CreaTVComandaGravacio", new object[] {
                    strTitol,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    fPreu,
                    strSMS,
                    fPVP,
                    strServiceID,
                    bTrigger,
                    nAdultContent}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCreaTVComandaGravacio(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CreaTVComandaGravacioAsync(
                    string strTitol,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    float fPreu,
                    string strSMS,
                    float fPVP,
                    string strServiceID,
                    bool bTrigger,
                    int nAdultContent) {
            this.CreaTVComandaGravacioAsync(strTitol, nPreviewTime, nPrioritat, nImmortalityTime, nActiveTime, nLifeExtension, strDiaIni, strHoraIni, strDiaFi, strHoraFi, nCodiID, fPreu, strSMS, fPVP, strServiceID, bTrigger, nAdultContent, null);
        }

        /// <remarks/>
        public void CreaTVComandaGravacioAsync(
                    string strTitol,
                    int nPreviewTime,
                    int nPrioritat,
                    int nImmortalityTime,
                    int nActiveTime,
                    int nLifeExtension,
                    string strDiaIni,
                    string strHoraIni,
                    string strDiaFi,
                    string strHoraFi,
                    int nCodiID,
                    float fPreu,
                    string strSMS,
                    float fPVP,
                    string strServiceID,
                    bool bTrigger,
                    int nAdultContent,
                    object userState) {
            if ((this.CreaTVComandaGravacioOperationCompleted == null)) {
                this.CreaTVComandaGravacioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreaTVComandaGravacioOperationCompleted);
            }
            this.InvokeAsync("CreaTVComandaGravacio", new object[] {
                    strTitol,
                    nPreviewTime,
                    nPrioritat,
                    nImmortalityTime,
                    nActiveTime,
                    nLifeExtension,
                    strDiaIni,
                    strHoraIni,
                    strDiaFi,
                    strHoraFi,
                    nCodiID,
                    fPreu,
                    strSMS,
                    fPVP,
                    strServiceID,
                    bTrigger,
                    nAdultContent}, this.CreaTVComandaGravacioOperationCompleted, userState);
        }

        private void OnCreaTVComandaGravacioOperationCompleted(object arg) {
            if ((this.CreaTVComandaGravacioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreaTVComandaGravacioCompleted(this, new CreaTVComandaGravacioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreaTVComandaGravacioV2", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreaTVComandaGravacioV2(string strARv2XML) {
            object[] results = this.Invoke("CreaTVComandaGravacioV2", new object[] {
                    strARv2XML});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreaTVComandaGravacioV2(string strARv2XML, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreaTVComandaGravacioV2", new object[] {
                    strARv2XML}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCreaTVComandaGravacioV2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CreaTVComandaGravacioV2Async(string strARv2XML) {
            this.CreaTVComandaGravacioV2Async(strARv2XML, null);
        }

        /// <remarks/>
        public void CreaTVComandaGravacioV2Async(string strARv2XML, object userState) {
            if ((this.CreaTVComandaGravacioV2OperationCompleted == null)) {
                this.CreaTVComandaGravacioV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreaTVComandaGravacioV2OperationCompleted);
            }
            this.InvokeAsync("CreaTVComandaGravacioV2", new object[] {
                    strARv2XML}, this.CreaTVComandaGravacioV2OperationCompleted, userState);
        }

        private void OnCreaTVComandaGravacioV2OperationCompleted(object arg) {
            if ((this.CreaTVComandaGravacioV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreaTVComandaGravacioV2Completed(this, new CreaTVComandaGravacioV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AturaTVComandaGravacio", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AturaTVComandaGravacio(int nCodiID) {
            object[] results = this.Invoke("AturaTVComandaGravacio", new object[] {
                    nCodiID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAturaTVComandaGravacio(int nCodiID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AturaTVComandaGravacio", new object[] {
                    nCodiID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndAturaTVComandaGravacio(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void AturaTVComandaGravacioAsync(int nCodiID) {
            this.AturaTVComandaGravacioAsync(nCodiID, null);
        }

        /// <remarks/>
        public void AturaTVComandaGravacioAsync(int nCodiID, object userState) {
            if ((this.AturaTVComandaGravacioOperationCompleted == null)) {
                this.AturaTVComandaGravacioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAturaTVComandaGravacioOperationCompleted);
            }
            this.InvokeAsync("AturaTVComandaGravacio", new object[] {
                    nCodiID}, this.AturaTVComandaGravacioOperationCompleted, userState);
        }

        private void OnAturaTVComandaGravacioOperationCompleted(object arg) {
            if ((this.AturaTVComandaGravacioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AturaTVComandaGravacioCompleted(this, new AturaTVComandaGravacioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminaTVComandaGravacio", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminaTVComandaGravacio(int nCodiID) {
            object[] results = this.Invoke("EliminaTVComandaGravacio", new object[] {
                    nCodiID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEliminaTVComandaGravacio(int nCodiID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminaTVComandaGravacio", new object[] {
                    nCodiID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEliminaTVComandaGravacio(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EliminaTVComandaGravacioAsync(int nCodiID) {
            this.EliminaTVComandaGravacioAsync(nCodiID, null);
        }

        /// <remarks/>
        public void EliminaTVComandaGravacioAsync(int nCodiID, object userState) {
            if ((this.EliminaTVComandaGravacioOperationCompleted == null)) {
                this.EliminaTVComandaGravacioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaTVComandaGravacioOperationCompleted);
            }
            this.InvokeAsync("EliminaTVComandaGravacio", new object[] {
                    nCodiID}, this.EliminaTVComandaGravacioOperationCompleted, userState);
        }

        private void OnEliminaTVComandaGravacioOperationCompleted(object arg) {
            if ((this.EliminaTVComandaGravacioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaTVComandaGravacioCompleted(this, new EliminaTVComandaGravacioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaCodiID", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaCodiID(int nCodiSTB, int nCodiID) {
            object[] results = this.Invoke("EnviaCodiID", new object[] {
                    nCodiSTB,
                    nCodiID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnviaCodiID(int nCodiSTB, int nCodiID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaCodiID", new object[] {
                    nCodiSTB,
                    nCodiID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEnviaCodiID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EnviaCodiIDAsync(int nCodiSTB, int nCodiID) {
            this.EnviaCodiIDAsync(nCodiSTB, nCodiID, null);
        }

        /// <remarks/>
        public void EnviaCodiIDAsync(int nCodiSTB, int nCodiID, object userState) {
            if ((this.EnviaCodiIDOperationCompleted == null)) {
                this.EnviaCodiIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaCodiIDOperationCompleted);
            }
            this.InvokeAsync("EnviaCodiID", new object[] {
                    nCodiSTB,
                    nCodiID}, this.EnviaCodiIDOperationCompleted, userState);
        }

        private void OnEnviaCodiIDOperationCompleted(object arg) {
            if ((this.EnviaCodiIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaCodiIDCompleted(this, new EnviaCodiIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaEntitlement", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaEntitlement(int nCodiSTB, int nCodiID, string strEntitlement) {
            object[] results = this.Invoke("EnviaEntitlement", new object[] {
                    nCodiSTB,
                    nCodiID,
                    strEntitlement});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnviaEntitlement(int nCodiSTB, int nCodiID, string strEntitlement, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaEntitlement", new object[] {
                    nCodiSTB,
                    nCodiID,
                    strEntitlement}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEnviaEntitlement(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EnviaEntitlementAsync(int nCodiSTB, int nCodiID, string strEntitlement) {
            this.EnviaEntitlementAsync(nCodiSTB, nCodiID, strEntitlement, null);
        }

        /// <remarks/>
        public void EnviaEntitlementAsync(int nCodiSTB, int nCodiID, string strEntitlement, object userState) {
            if ((this.EnviaEntitlementOperationCompleted == null)) {
                this.EnviaEntitlementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaEntitlementOperationCompleted);
            }
            this.InvokeAsync("EnviaEntitlement", new object[] {
                    nCodiSTB,
                    nCodiID,
                    strEntitlement}, this.EnviaEntitlementOperationCompleted, userState);
        }

        private void OnEnviaEntitlementOperationCompleted(object arg) {
            if ((this.EnviaEntitlementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaEntitlementCompleted(this, new EnviaEntitlementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaEntitlementV2", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaEntitlementV2(
                    int nCodiSTB,
                    int nVersion,
                    int nActivationId,
                    int nCodiID,
                    int nActivationDuration,
                    long lActiveUntilDateUTC,
                    bool bNumberViewsMode,
                    int nNumberViews,
                    int nActiveTimeAfterView,
                    int nActivePeriodExtensionAfterView,
                    int nAliveTimeAfterActivation,
                    int nLifeExtensionAfterActivation,
                    int nAlifeTimeAfterView,
                    int nLifeExtensionAfterView,
                    float fNewPrice,
                    string strEntitlement) {
            object[] results = this.Invoke("EnviaEntitlementV2", new object[] {
                    nCodiSTB,
                    nVersion,
                    nActivationId,
                    nCodiID,
                    nActivationDuration,
                    lActiveUntilDateUTC,
                    bNumberViewsMode,
                    nNumberViews,
                    nActiveTimeAfterView,
                    nActivePeriodExtensionAfterView,
                    nAliveTimeAfterActivation,
                    nLifeExtensionAfterActivation,
                    nAlifeTimeAfterView,
                    nLifeExtensionAfterView,
                    fNewPrice,
                    strEntitlement});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnviaEntitlementV2(
                    int nCodiSTB,
                    int nVersion,
                    int nActivationId,
                    int nCodiID,
                    int nActivationDuration,
                    long lActiveUntilDateUTC,
                    bool bNumberViewsMode,
                    int nNumberViews,
                    int nActiveTimeAfterView,
                    int nActivePeriodExtensionAfterView,
                    int nAliveTimeAfterActivation,
                    int nLifeExtensionAfterActivation,
                    int nAlifeTimeAfterView,
                    int nLifeExtensionAfterView,
                    float fNewPrice,
                    string strEntitlement,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("EnviaEntitlementV2", new object[] {
                    nCodiSTB,
                    nVersion,
                    nActivationId,
                    nCodiID,
                    nActivationDuration,
                    lActiveUntilDateUTC,
                    bNumberViewsMode,
                    nNumberViews,
                    nActiveTimeAfterView,
                    nActivePeriodExtensionAfterView,
                    nAliveTimeAfterActivation,
                    nLifeExtensionAfterActivation,
                    nAlifeTimeAfterView,
                    nLifeExtensionAfterView,
                    fNewPrice,
                    strEntitlement}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEnviaEntitlementV2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EnviaEntitlementV2Async(
                    int nCodiSTB,
                    int nVersion,
                    int nActivationId,
                    int nCodiID,
                    int nActivationDuration,
                    long lActiveUntilDateUTC,
                    bool bNumberViewsMode,
                    int nNumberViews,
                    int nActiveTimeAfterView,
                    int nActivePeriodExtensionAfterView,
                    int nAliveTimeAfterActivation,
                    int nLifeExtensionAfterActivation,
                    int nAlifeTimeAfterView,
                    int nLifeExtensionAfterView,
                    float fNewPrice,
                    string strEntitlement) {
            this.EnviaEntitlementV2Async(nCodiSTB, nVersion, nActivationId, nCodiID, nActivationDuration, lActiveUntilDateUTC, bNumberViewsMode, nNumberViews, nActiveTimeAfterView, nActivePeriodExtensionAfterView, nAliveTimeAfterActivation, nLifeExtensionAfterActivation, nAlifeTimeAfterView, nLifeExtensionAfterView, fNewPrice, strEntitlement, null);
        }

        /// <remarks/>
        public void EnviaEntitlementV2Async(
                    int nCodiSTB,
                    int nVersion,
                    int nActivationId,
                    int nCodiID,
                    int nActivationDuration,
                    long lActiveUntilDateUTC,
                    bool bNumberViewsMode,
                    int nNumberViews,
                    int nActiveTimeAfterView,
                    int nActivePeriodExtensionAfterView,
                    int nAliveTimeAfterActivation,
                    int nLifeExtensionAfterActivation,
                    int nAlifeTimeAfterView,
                    int nLifeExtensionAfterView,
                    float fNewPrice,
                    string strEntitlement,
                    object userState) {
            if ((this.EnviaEntitlementV2OperationCompleted == null)) {
                this.EnviaEntitlementV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaEntitlementV2OperationCompleted);
            }
            this.InvokeAsync("EnviaEntitlementV2", new object[] {
                    nCodiSTB,
                    nVersion,
                    nActivationId,
                    nCodiID,
                    nActivationDuration,
                    lActiveUntilDateUTC,
                    bNumberViewsMode,
                    nNumberViews,
                    nActiveTimeAfterView,
                    nActivePeriodExtensionAfterView,
                    nAliveTimeAfterActivation,
                    nLifeExtensionAfterActivation,
                    nAlifeTimeAfterView,
                    nLifeExtensionAfterView,
                    fNewPrice,
                    strEntitlement}, this.EnviaEntitlementV2OperationCompleted, userState);
        }

        private void OnEnviaEntitlementV2OperationCompleted(object arg) {
            if ((this.EnviaEntitlementV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaEntitlementV2Completed(this, new EnviaEntitlementV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaComandaStandBy", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaComandaStandBy(int nCodiSTB, uint nSleepTime) {
            object[] results = this.Invoke("EnviaComandaStandBy", new object[] {
                    nCodiSTB,
                    nSleepTime});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnviaComandaStandBy(int nCodiSTB, uint nSleepTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaComandaStandBy", new object[] {
                    nCodiSTB,
                    nSleepTime}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEnviaComandaStandBy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EnviaComandaStandByAsync(int nCodiSTB, uint nSleepTime) {
            this.EnviaComandaStandByAsync(nCodiSTB, nSleepTime, null);
        }

        /// <remarks/>
        public void EnviaComandaStandByAsync(int nCodiSTB, uint nSleepTime, object userState) {
            if ((this.EnviaComandaStandByOperationCompleted == null)) {
                this.EnviaComandaStandByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaComandaStandByOperationCompleted);
            }
            this.InvokeAsync("EnviaComandaStandBy", new object[] {
                    nCodiSTB,
                    nSleepTime}, this.EnviaComandaStandByOperationCompleted, userState);
        }

        private void OnEnviaComandaStandByOperationCompleted(object arg) {
            if ((this.EnviaComandaStandByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaComandaStandByCompleted(this, new EnviaComandaStandByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaXML", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaXML(string strXmlFile, int nDataChannel, string strServidorFTP, string strPathOrigenFTP, string strUsuariFTP, string strPasswordFTP) {
            object[] results = this.Invoke("EnviaXML", new object[] {
                    strXmlFile,
                    nDataChannel,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnviaXML(string strXmlFile, int nDataChannel, string strServidorFTP, string strPathOrigenFTP, string strUsuariFTP, string strPasswordFTP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaXML", new object[] {
                    strXmlFile,
                    nDataChannel,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEnviaXML(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EnviaXMLAsync(string strXmlFile, int nDataChannel, string strServidorFTP, string strPathOrigenFTP, string strUsuariFTP, string strPasswordFTP) {
            this.EnviaXMLAsync(strXmlFile, nDataChannel, strServidorFTP, strPathOrigenFTP, strUsuariFTP, strPasswordFTP, null);
        }

        /// <remarks/>
        public void EnviaXMLAsync(string strXmlFile, int nDataChannel, string strServidorFTP, string strPathOrigenFTP, string strUsuariFTP, string strPasswordFTP, object userState) {
            if ((this.EnviaXMLOperationCompleted == null)) {
                this.EnviaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaXMLOperationCompleted);
            }
            this.InvokeAsync("EnviaXML", new object[] {
                    strXmlFile,
                    nDataChannel,
                    strServidorFTP,
                    strPathOrigenFTP,
                    strUsuariFTP,
                    strPasswordFTP}, this.EnviaXMLOperationCompleted, userState);
        }

        private void OnEnviaXMLOperationCompleted(object arg) {
            if ((this.EnviaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaXMLCompleted(this, new EnviaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AturaXML", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AturaXML(int nDataChannel) {
            object[] results = this.Invoke("AturaXML", new object[] {
                    nDataChannel});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAturaXML(int nDataChannel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AturaXML", new object[] {
                    nDataChannel}, callback, asyncState);
        }

        /// <remarks/>
        public string EndAturaXML(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void AturaXMLAsync(int nDataChannel) {
            this.AturaXMLAsync(nDataChannel, null);
        }

        /// <remarks/>
        public void AturaXMLAsync(int nDataChannel, object userState) {
            if ((this.AturaXMLOperationCompleted == null)) {
                this.AturaXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAturaXMLOperationCompleted);
            }
            this.InvokeAsync("AturaXML", new object[] {
                    nDataChannel}, this.AturaXMLOperationCompleted, userState);
        }

        private void OnAturaXMLOperationCompleted(object arg) {
            if ((this.AturaXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AturaXMLCompleted(this, new AturaXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminaContingutSTB", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminaContingutSTB(int nCodiID) {
            object[] results = this.Invoke("EliminaContingutSTB", new object[] {
                    nCodiID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEliminaContingutSTB(int nCodiID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminaContingutSTB", new object[] {
                    nCodiID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEliminaContingutSTB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EliminaContingutSTBAsync(int nCodiID) {
            this.EliminaContingutSTBAsync(nCodiID, null);
        }

        /// <remarks/>
        public void EliminaContingutSTBAsync(int nCodiID, object userState) {
            if ((this.EliminaContingutSTBOperationCompleted == null)) {
                this.EliminaContingutSTBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaContingutSTBOperationCompleted);
            }
            this.InvokeAsync("EliminaContingutSTB", new object[] {
                    nCodiID}, this.EliminaContingutSTBOperationCompleted, userState);
        }

        private void OnEliminaContingutSTBOperationCompleted(object arg) {
            if ((this.EliminaContingutSTBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaContingutSTBCompleted(this, new EliminaContingutSTBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificaContingut_content_life_mod_command", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ModificaContingut_content_life_mod_command(int nCodiID, long lExpirationDateUTC, int nExpirationTimeAfterCommand, int nExpirationExtension, long lImmortalityDateUTC, int nImmortalTimeAfterCommand, int nImmortalityExtension) {
            object[] results = this.Invoke("ModificaContingut_content_life_mod_command", new object[] {
                    nCodiID,
                    lExpirationDateUTC,
                    nExpirationTimeAfterCommand,
                    nExpirationExtension,
                    lImmortalityDateUTC,
                    nImmortalTimeAfterCommand,
                    nImmortalityExtension});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginModificaContingut_content_life_mod_command(int nCodiID, long lExpirationDateUTC, int nExpirationTimeAfterCommand, int nExpirationExtension, long lImmortalityDateUTC, int nImmortalTimeAfterCommand, int nImmortalityExtension, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ModificaContingut_content_life_mod_command", new object[] {
                    nCodiID,
                    lExpirationDateUTC,
                    nExpirationTimeAfterCommand,
                    nExpirationExtension,
                    lImmortalityDateUTC,
                    nImmortalTimeAfterCommand,
                    nImmortalityExtension}, callback, asyncState);
        }

        /// <remarks/>
        public string EndModificaContingut_content_life_mod_command(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ModificaContingut_content_life_mod_commandAsync(int nCodiID, long lExpirationDateUTC, int nExpirationTimeAfterCommand, int nExpirationExtension, long lImmortalityDateUTC, int nImmortalTimeAfterCommand, int nImmortalityExtension) {
            this.ModificaContingut_content_life_mod_commandAsync(nCodiID, lExpirationDateUTC, nExpirationTimeAfterCommand, nExpirationExtension, lImmortalityDateUTC, nImmortalTimeAfterCommand, nImmortalityExtension, null);
        }

        /// <remarks/>
        public void ModificaContingut_content_life_mod_commandAsync(int nCodiID, long lExpirationDateUTC, int nExpirationTimeAfterCommand, int nExpirationExtension, long lImmortalityDateUTC, int nImmortalTimeAfterCommand, int nImmortalityExtension, object userState) {
            if ((this.ModificaContingut_content_life_mod_commandOperationCompleted == null)) {
                this.ModificaContingut_content_life_mod_commandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificaContingut_content_life_mod_commandOperationCompleted);
            }
            this.InvokeAsync("ModificaContingut_content_life_mod_command", new object[] {
                    nCodiID,
                    lExpirationDateUTC,
                    nExpirationTimeAfterCommand,
                    nExpirationExtension,
                    lImmortalityDateUTC,
                    nImmortalTimeAfterCommand,
                    nImmortalityExtension}, this.ModificaContingut_content_life_mod_commandOperationCompleted, userState);
        }

        private void OnModificaContingut_content_life_mod_commandOperationCompleted(object arg) {
            if ((this.ModificaContingut_content_life_mod_commandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificaContingut_content_life_mod_commandCompleted(this, new ModificaContingut_content_life_mod_commandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaComandaBase64", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaComandaBase64(int nCodiSTB, string strComandaBase64) {
            object[] results = this.Invoke("EnviaComandaBase64", new object[] {
                    nCodiSTB,
                    strComandaBase64});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnviaComandaBase64(int nCodiSTB, string strComandaBase64, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaComandaBase64", new object[] {
                    nCodiSTB,
                    strComandaBase64}, callback, asyncState);
        }

        /// <remarks/>
        public string EndEnviaComandaBase64(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void EnviaComandaBase64Async(int nCodiSTB, string strComandaBase64) {
            this.EnviaComandaBase64Async(nCodiSTB, strComandaBase64, null);
        }

        /// <remarks/>
        public void EnviaComandaBase64Async(int nCodiSTB, string strComandaBase64, object userState) {
            if ((this.EnviaComandaBase64OperationCompleted == null)) {
                this.EnviaComandaBase64OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaComandaBase64OperationCompleted);
            }
            this.InvokeAsync("EnviaComandaBase64", new object[] {
                    nCodiSTB,
                    strComandaBase64}, this.EnviaComandaBase64OperationCompleted, userState);
        }

        private void OnEnviaComandaBase64OperationCompleted(object arg) {
            if ((this.EnviaComandaBase64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaComandaBase64Completed(this, new EnviaComandaBase64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CEncapsulatorContent {

        private object[] m_aListCodiIDField;

        private object[] m_aListEnviatField;

        /// <remarks/>
        public object[] m_aListCodiID {
            get {
                return this.m_aListCodiIDField;
            }
            set {
                this.m_aListCodiIDField = value;
            }
        }

        /// <remarks/>
        public object[] m_aListEnviat {
            get {
                return this.m_aListEnviatField;
            }
            set {
                this.m_aListEnviatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void TestWSCompletedEventHandler(object sender, TestWSCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal TestWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void TestAppCompletedEventHandler(object sender, TestAppCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestAppCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal TestAppCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EncapsulatorHasSentContentCompletedEventHandler(object sender, EncapsulatorHasSentContentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncapsulatorHasSentContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EncapsulatorHasSentContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }

        /// <remarks/>
        public CEncapsulatorContent itemEncapsulatorContent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CEncapsulatorContent)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CreaScheduleItemCompletedEventHandler(object sender, CreaScheduleItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreaScheduleItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal CreaScheduleItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ModificaScheduleItemCompletedEventHandler(object sender, ModificaScheduleItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificaScheduleItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal ModificaScheduleItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EliminaScheduleItemCompletedEventHandler(object sender, EliminaScheduleItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaScheduleItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EliminaScheduleItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CreaTVComandaGravacioCompletedEventHandler(object sender, CreaTVComandaGravacioCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreaTVComandaGravacioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal CreaTVComandaGravacioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CreaTVComandaGravacioV2CompletedEventHandler(object sender, CreaTVComandaGravacioV2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreaTVComandaGravacioV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal CreaTVComandaGravacioV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void AturaTVComandaGravacioCompletedEventHandler(object sender, AturaTVComandaGravacioCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AturaTVComandaGravacioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal AturaTVComandaGravacioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EliminaTVComandaGravacioCompletedEventHandler(object sender, EliminaTVComandaGravacioCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaTVComandaGravacioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EliminaTVComandaGravacioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnviaCodiIDCompletedEventHandler(object sender, EnviaCodiIDCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaCodiIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EnviaCodiIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnviaEntitlementCompletedEventHandler(object sender, EnviaEntitlementCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaEntitlementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EnviaEntitlementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnviaEntitlementV2CompletedEventHandler(object sender, EnviaEntitlementV2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaEntitlementV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EnviaEntitlementV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnviaComandaStandByCompletedEventHandler(object sender, EnviaComandaStandByCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaComandaStandByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EnviaComandaStandByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnviaXMLCompletedEventHandler(object sender, EnviaXMLCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EnviaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void AturaXMLCompletedEventHandler(object sender, AturaXMLCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AturaXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal AturaXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EliminaContingutSTBCompletedEventHandler(object sender, EliminaContingutSTBCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaContingutSTBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EliminaContingutSTBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ModificaContingut_content_life_mod_commandCompletedEventHandler(object sender, ModificaContingut_content_life_mod_commandCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificaContingut_content_life_mod_commandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal ModificaContingut_content_life_mod_commandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnviaComandaBase64CompletedEventHandler(object sender, EnviaComandaBase64CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaComandaBase64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal EnviaComandaBase64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
