//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBNotificationPusherService
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acknowledgment", Namespace="http://schemas.datacontract.org/2004/07/DBNotificationPusherService")]
    public enum Acknowledgment : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAK = 1,
    }
}
namespace DBNotificationPusherService.DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/DBNotificationPusherService.DTO")]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime LastLockedScheduleNotificationTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLockedScheduleNotificationTime
        {
            get
            {
                return this.LastLockedScheduleNotificationTimeField;
            }
            set
            {
                this.LastLockedScheduleNotificationTimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="INotificationPusher", CallbackContract=typeof(INotificationPusherCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface INotificationPusher
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationPusher/Subscribe")]
    void Subscribe(string uuid);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationPusher/Unsubscribe")]
    void Unsubscribe(string uuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationPusher/KeepAlive", ReplyAction="http://tempuri.org/INotificationPusher/KeepAliveResponse")]
    DBNotificationPusherService.Acknowledgment KeepAlive();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INotificationPusherCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotificationPusher/SendNotification")]
    void SendNotification(DBNotificationPusherService.DTO.Notification objNotification);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INotificationPusherChannel : INotificationPusher, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NotificationPusherClient : System.ServiceModel.DuplexClientBase<INotificationPusher>, INotificationPusher
{
    
    public NotificationPusherClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public NotificationPusherClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public NotificationPusherClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotificationPusherClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotificationPusherClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Subscribe(string uuid)
    {
        base.Channel.Subscribe(uuid);
    }
    
    public void Unsubscribe(string uuid)
    {
        base.Channel.Unsubscribe(uuid);
    }
    
    public DBNotificationPusherService.Acknowledgment KeepAlive()
    {
        return base.Channel.KeepAlive();
    }
}
