//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class configuration
{


    private string languageField;
    private string iPModeField;
    private string iPv4AddressField;
    private string iPv6AddressField;
    private bool dHCPRerouteField;
    private int lANPortField;
    private int serverReceiveTimeoutField;
    private string AllowedIPListField;
    private string mediaDirectoryField;
    private string ReqDirectoryField;
    private int PriorityField;
    private string serverNameField;
    private bool IPv6DisabledField;
    private bool useUPNPField;
    private int serverPortField;
    private int logFileSizeKBField;
    private bool enable_Error_ReportingField;
    private bool enable_Storage_ManagementField;
    private int maxMediaFolderSizeMBField;
    private string sMTPFromAddressField;
    private string sMTPServerField;
    private int sMTPPortField;
    private string sMTPUsernameField;
    private string sMTPPasswordField;
    private bool sMTPSSLField;
    private int deleteFilesOlderThanDaysField;

    /// <remarks/>
    public string Language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }

    /// <remarks/>
    public string IPMode
    {
        get
        {
            return this.iPModeField;
        }
        set
        {
            this.iPModeField = value;
        }
    }
    /// <remarks/>
    public string IPv4Address
    {
        get
        {
            return this.iPv4AddressField;
        }
        set
        {
            this.iPv4AddressField = value;
        }
    }

    /// <remarks/>
    public string IPv6Address
    {
        get
        {
            return this.iPv6AddressField;
        }
        set
        {
            this.iPv6AddressField = value;
        }
    }

    /// <remarks/>
    public bool DHCPReroute
    {
        get
        {
            return this.dHCPRerouteField;
        }
        set
        {
            this.dHCPRerouteField = value;
        }
    }
    /// <remarks/>
    public int LANPort
    {
        get
        {
            return this.lANPortField;
        }
        set
        {
            this.lANPortField = value;
        }
    }

    /// <remarks/>
    public int ServerReceiveTimeout
    {
        get
        {
            return this.serverReceiveTimeoutField;
        }
        set
        {
            this.serverReceiveTimeoutField = value;
        }
    }

    /// <remarks/>
    public string AllowedIPList
    {
        get
        {
            return this.AllowedIPListField;
        }
        set
        {
            this.AllowedIPListField = value;
        }
    }

    /// <remarks/>
    public string MediaDirectory
    {
        get
        {
            return this.mediaDirectoryField;
        }
        set
        {
            this.mediaDirectoryField = value;
        }
    }

    public string ReqDirectory
    {
        get
        {
            return this.ReqDirectoryField;
        }
        set
        {
            this.ReqDirectoryField = value;
        }
    }

    /// <remarks/>
    public int Priority
    {
        get
        {
            return this.PriorityField;
        }
        set
        {
            this.PriorityField = value;
        }
    }

    /// <remarks/>
    public string ServerName
    {
        get
        {
            return this.serverNameField;
        }
        set
        {
            this.serverNameField = value;
        }
    }

    public bool IPv6Disabled
    {
        get
        {
            return this.IPv6DisabledField;
        }
        set
        {
            this.IPv6DisabledField = value;
        }
    }

    /// <remarks/>
    public bool UseUPNP
    {
        get
        {
            return this.useUPNPField;
        }
        set
        {
            this.useUPNPField = value;
        }
    }

    /// <remarks/>
    public int ServerPort
    {
        get
        {
            return this.serverPortField;
        }
        set
        {
            this.serverPortField = value;
        }
    }

    /// <remarks/>
    public int LogFileSizeKB
    {
        get
        {
            return this.logFileSizeKBField;
        }
        set
        {
            this.logFileSizeKBField = value;
        }
    }

    public bool Enable_Error_Reporting
    {
        get
        {
            return this.enable_Error_ReportingField;
        }
        set
        {
            this.enable_Error_ReportingField = value;
        }
    }


    /// <remarks/>
    public bool Enable_Storage_Management
    {
        get
        {
            return this.enable_Storage_ManagementField;
        }
        set
        {
            this.enable_Storage_ManagementField = value;
        }
    }

    /// <remarks/>
    public int MaxMediaFolderSizeMB
    {
        get
        {
            return this.maxMediaFolderSizeMBField;
        }
        set
        {
            this.maxMediaFolderSizeMBField = value;
        }
    }

    /// <remarks/>
    public string SMTPFromAddress
    {
        get
        {
            return this.sMTPFromAddressField;
        }
        set
        {
            this.sMTPFromAddressField = value;
        }
    }

    /// <remarks/>
    public string SMTPServer
    {
        get
        {
            return this.sMTPServerField;
        }
        set
        {
            this.sMTPServerField = value;
        }
    }

    /// <remarks/>
    public int SMTPPort
    {
        get
        {
            return this.sMTPPortField;
        }
        set
        {
            this.sMTPPortField = value;
        }
    }

    /// <remarks/>
    public string SMTPUsername
    {
        get
        {
            return this.sMTPUsernameField;
        }
        set
        {
            this.sMTPUsernameField = value;
        }
    }

    /// <remarks/>
    public string SMTPPassword
    {
        get
        {
            return this.sMTPPasswordField;
        }
        set
        {
            this.sMTPPasswordField = value;
        }
    }

    /// <remarks/>
    public bool SMTPSSL
    {
        get
        {
            return this.sMTPSSLField;
        }
        set
        {
            this.sMTPSSLField = value;
        }
    }

    /// <remarks/>
    public int DeleteFilesOlderThanDays
    {
        get
        {
            return this.deleteFilesOlderThanDaysField;
        }
        set
        {
            this.deleteFilesOlderThanDaysField = value;
        }
    }
   
}
