//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTV.MAM.WebApp.Admin {
    
    
    public partial class SystemEncapsulator_aspx {
        
        /// <summary>
        /// ctrlConfigurationHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MTV.MAM.WebApp.Admin.Modules.SystemEncapsulatorControl ctrlConfigurationHome;
    }
}
