//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MTV.EventDequeuer.Service.Catalog
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mebsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mebsEntities object using the connection string found in the 'mebsEntities' section of the application configuration file.
        /// </summary>
        public mebsEntities() : base("name=mebsEntities", "mebsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mebsEntities object.
        /// </summary>
        public mebsEntities(string connectionString) : base(connectionString, "mebsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mebsEntities object.
        /// </summary>
        public mebsEntities(EntityConnection connection) : base(connection, "mebsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mebs_settings> mebs_settings
        {
            get
            {
                if ((_mebs_settings == null))
                {
                    _mebs_settings = base.CreateObjectSet<mebs_settings>("mebs_settings");
                }
                return _mebs_settings;
            }
        }
        private ObjectSet<mebs_settings> _mebs_settings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mebs_settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomebs_settings(mebs_settings mebs_settings)
        {
            base.AddObject("mebs_settings", mebs_settings);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int ScheduleSetLockValue()
        {
            return base.ExecuteFunction("ScheduleSetLockValue");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int IngestaSetIsExpiredValue()
        {
            return base.ExecuteFunction("IngestaSetIsExpiredValue");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mebsModel", Name="mebs_settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mebs_settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mebs_settings object.
        /// </summary>
        /// <param name="idSetting">Initial value of the IdSetting property.</param>
        /// <param name="visibility">Initial value of the Visibility property.</param>
        public static mebs_settings Createmebs_settings(global::System.Int32 idSetting, global::System.String visibility)
        {
            mebs_settings mebs_settings = new mebs_settings();
            mebs_settings.IdSetting = idSetting;
            mebs_settings.Visibility = visibility;
            return mebs_settings;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSetting
        {
            get
            {
                return _IdSetting;
            }
            set
            {
                if (_IdSetting != value)
                {
                    OnIdSettingChanging(value);
                    ReportPropertyChanging("IdSetting");
                    _IdSetting = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdSetting");
                    OnIdSettingChanged();
                }
            }
        }
        private global::System.Int32 _IdSetting;
        partial void OnIdSettingChanging(global::System.Int32 value);
        partial void OnIdSettingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SettingName
        {
            get
            {
                return _SettingName;
            }
            set
            {
                OnSettingNameChanging(value);
                ReportPropertyChanging("SettingName");
                _SettingName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SettingName");
                OnSettingNameChanged();
            }
        }
        private global::System.String _SettingName;
        partial void OnSettingNameChanging(global::System.String value);
        partial void OnSettingNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SettingValue
        {
            get
            {
                return _SettingValue;
            }
            set
            {
                OnSettingValueChanging(value);
                ReportPropertyChanging("SettingValue");
                _SettingValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SettingValue");
                OnSettingValueChanged();
            }
        }
        private global::System.String _SettingValue;
        partial void OnSettingValueChanging(global::System.String value);
        partial void OnSettingValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Visibility
        {
            get
            {
                return _Visibility;
            }
            set
            {
                OnVisibilityChanging(value);
                ReportPropertyChanging("Visibility");
                _Visibility = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Visibility");
                OnVisibilityChanged();
            }
        }
        private global::System.String _Visibility;
        partial void OnVisibilityChanging(global::System.String value);
        partial void OnVisibilityChanged();

        #endregion
    
    }

    #endregion
    
}
